### ISSUE TITLE
pinkie-promise is missing  in leveldown?

### ISSUE THREAD

**Issue by youkaisteve** [Level/levelup#373]
when I install level,error occurs as follows:
/****************************************************************************************************************************/
> leveldown@1.4.2 install e:\Workspace\Sec\pull-data\src\node_module
_modules\leveldown
> prebuild --download

prebuild WARN install EPERM, access 'C:\Users\Administrator\AppData\
cache'
module.js:338
    throw err;
          ^
Error: Cannot find module 'pinkie-promise'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (e:\Workspace\Sec\pull-data\src\node_modul
ode_modules\har-validator\lib\index.js:3:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Fil
node_modules\\npm\\bin\\npm-cli.js" "install" "level" "--save"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
/****************************************************************************************************************************/

'pinkie-promise' is missing in package.json?

**Comment by rvagg** [comment]
```
 at Object. (e:\Workspace\Sec\pull-data\src\node_modul
ode_modules\har-validator\lib\index.js:3:15)
```

it's a problem with [har-validator](https://github.com/ahmadnassri/har-validator), not level, although it's included in har-validator's package.json so I suggest you remove your node_modules directory and `npm install` from scratch, it seems like you may have inconsistent state somewhere in there.

**Comment by youkaisteve** [comment]
I remove the node_modules and reinstall level,it works.Thank you !
