### ISSUE TITLE
Failed to require LevelDOWN (Module version mismatch. Expected 49, got 48.)

### ISSUE THREAD

**Issue by HR** [Level/levelup#395]
I'm getting the follwing error for both node 6.0.0 and node 6.1.0 for leveldown@1.4.6 which [apparantly added support for node v6](https://github.com/Level/leveldown/releases)
```bash
LevelUPError: Failed to require LevelDOWN (Module version mismatch. Expected 49, got 48.). Try `npm install leveldown` if it's missing
    at requireError (/Users/HR/GitHub/Crypter/node_modules/levelup/lib/util.js:60:10)
    at getLevelDOWN (/Users/HR/GitHub/Crypter/node_modules/levelup/lib/util.js:54:11)
    at Db.LevelUP.open (/Users/HR/GitHub/Crypter/node_modules/levelup/lib/levelup.js:114:37)
    at Db.LevelUP (/Users/HR/GitHub/Crypter/node_modules/levelup/lib/levelup.js:87:8)
    at new Db (/Users/HR/GitHub/Crypter/src/Db.js:24:11)
    at /Users/HR/GitHub/Crypter/index.js:42:18
    at init (/Users/HR/GitHub/Crypter/index.js:40:10)
    at App.<anonymous> (/Users/HR/GitHub/Crypter/index.js:74:3)
    at emitOne (events.js:101:20)
    at App.emit (events.js:188:7)
```
I have tried ```npm rebuild``` for both node versions but found no success

**Comment by juliangruber** [comment]
this error most likely appears when you install leveldown using a different node version than when running the process. Something like

```bash
$ nvm use 4
$ npm install leveldown
$ nvm use 6
$ node index.js
```

your particular case might be a bit more complicated.

Can you confirm this is not the issue? Please post the results of

```bash
$ node -v
$ npm -v
$ npm --help | tail -1
```

If you're using electron, this can happen too, as electron bundles its own version of node.

**Comment by juliangruber** [comment]
Ah ok, so it is an electron related error. Can you try again with electron@1.1.3?

**Comment by HR** [comment]
Just check and it works for electron@1.1.3 . What was the problem? Is there a way to fix this for the later releases of electron?

**Comment by juliangruber** [comment]
ok, this then looks like it's this bug: https://github.com/electron/electron/issues/5851, and the thread should provide you with all the information you need :)
