### ISSUE TITLE
The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by Kaperstone** [Level/levelup#476]
I've been fighting this for two days, gave the pc a reboot, checked the processes if there is any "level" process running reinstalled `level` several times, checked if there are any leftovers in the npm_modules, installed, this error still occurred, no clue why is it still showing me.
I even deleted level database (?) folder, deleted level from %APPDATA%/npm_cache

The error still appears and I don't know what else can I do to unlock
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: LockFile ./leveldb/ses/LOCK: The process cannot access the file because it is being used by another process.

    at \node_modules\levelup\lib\levelup.js:117:34
    at \node_modules\abstract-leveldown\abstract-leveldown.js:39:16
```

EDIT: I'm using Windows 10 Home 1703

**Comment by Kaperstone** [comment]
Code opens the database on the same path twice.
