### ISSUE TITLE
can't not install benchmark or run

### ISSUE THREAD

**Issue by morolt** [Level/levelup#636]
```
npm install                                                                                                                                         10:32:52

> leveldown@1.9.0 install /Users/apple/www/temp/levelup/test/benchmarks/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.0 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
  LIBTOOL-STATIC Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/apple/.node-gyp/10.15.0/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/apple/.node-gyp/10.15.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/apple/.node-gyp/10.15.0/include/node/node.h:169:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/apple/.node-gyp/10.15.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/apple/.node-gyp/10.15.0/include/node/node.h:162:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/apple/.node-gyp/10.15.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/batch.cc:3:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/apple/.node-gyp/10.15.0/include/node/node.h:176:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/apple/.node-gyp/10.15.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/batch.cc:5:
In file included from ../src/database.h:18:
../src/leveldown.h:16:17: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  return (!obj->ToObject().IsEmpty()
                ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/batch.cc:5:
In file included from ../src/database.h:18:
../src/leveldown.h:17:39: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    && node::Buffer::HasInstance(obj->ToObject()))
                                      ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/batch.cc:5:
In file included from ../src/database.h:18:
../src/leveldown.h:18:33: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    ? node::Buffer::Length(obj->ToObject())
                                ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
In file included from ../src/batch.cc:8:
../src/common.h:32:26: warning: 'Uint32Value' is deprecated [-Wdeprecated-declarations]
    ? options->Get(key)->Uint32Value()
                         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2477:3: note: 'Uint32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
  ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:42:67: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  Database* database = Nan::ObjectWrap::Unwrap<Database>(info[0]->ToObject());
                                                                  ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:91:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^
../src/leveldown.h:53:21: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
  } else if (!from->ToObject().IsEmpty()                                       \
                    ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:91:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^
../src/leveldown.h:54:42: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
      && node::Buffer::HasInstance(from->ToObject())) {                        \
                                         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:91:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^
../src/leveldown.h:55:44: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
    to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                           ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:91:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^
../src/leveldown.h:56:42: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
    to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:92:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
  ^
../src/leveldown.h:53:21: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
  } else if (!from->ToObject().IsEmpty()                                       \
                    ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:92:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
  ^
../src/leveldown.h:54:42: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
      && node::Buffer::HasInstance(from->ToObject())) {                        \
                                         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:92:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
  ^
../src/leveldown.h:55:44: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
    to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                           ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:92:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(value, valueBuffer, value)
  ^
../src/leveldown.h:56:42: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
    to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:110:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^
../src/leveldown.h:53:21: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
  } else if (!from->ToObject().IsEmpty()                                       \
                    ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:110:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^
../src/leveldown.h:54:42: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
      && node::Buffer::HasInstance(from->ToObject())) {                        \
                                         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:110:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^
../src/leveldown.h:55:44: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
    to ## Sz_ = node::Buffer::Length(from->ToObject());                        \
                                           ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/batch.cc:110:3: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  LD_STRING_OR_BUFFER_TO_SLICE(key, keyBuffer, key)
  ^
../src/leveldown.h:56:42: note: expanded from macro 'LD_STRING_OR_BUFFER_TO_SLICE'
    to ## Ch_ = node::Buffer::Data(from->ToObject());                          \
                                         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/apple/.node-gyp/10.15.0/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
21 warnings and 1 error generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@10/10.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/Cellar/node@10/10.15.0/bin/node" "/usr/local/Cellar/node@10/10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/apple/www/temp/levelup/test/benchmarks/node_modules/leveldown
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.9.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2019-01-09T02_33_47_920Z-debug.log
```
update levelup version to 4.0.0, then
```
npm install                                                                                                                                 13.7s  10:26:14

> leveldown@4.0.1 install /Users/apple/www/temp/levelup/test/benchmarks/node_modules/leveldown
> prebuild-install || node-gyp rebuild

npm notice created a lockfile as package-lock.json. You should commit this file.
added 26 packages from 39 contributors in 16.62s
```
benchmark
```
node ./                                                                                                                                     17.1s  10:26:34
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'xtend'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/apple/www/temp/levelup/lib/levelup.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by morolt** [comment]
update package.json 
```
{
  "name": "levelup-benchmarks",
  "version": "0.0.0",
  "description": "benchmarks for LevelUP",
  "main": "index.js",
  "scripts": {
    "postinstall": "cd ../../ && npm install"
  },
  "private": true,
  "dependencies": {
    "async": "^2.6.1",
    "benchmark": "^2.1.4",
    "colors": "~0.6.0-1",
    "leveldown": "^4.0.1",
    "levelup": "*",
    "rimraf": "^2.6.3",
    "sqlite3": "*"
  }
}
```
then fixed
