### ISSUE TITLE
Levelup currenly not installing on node v12.x.x (osx)

### ISSUE THREAD

**Issue by fergiemcdowall** [Level/levelup#671]
I (prematurely) installed node v12.9.1 because of my love for `Array.flat()`. However `levelup` does not seem to install on v12.9.1

This is probably a known issue as I can see that [.travis.yml](https://github.com/Level/levelup/blob/c3845eea4547a829b05548c092b84d5cc30b8e46/.travis.yml) only references `6`, `8`, `10` and `stable`

**Comment by vweevers** [comment]
Which version of levelup? Are you combining it with leveldown? What version? What error do you get?

**Comment by fergiemcdowall** [comment]
node v12.9.1
levelup@4.1.0

Everything works fine on node 10. However, when I upgrade to node 12 levelup can no longer be installed. Problem seems to originate when leveldown builds a leveldb, but since I never use these libs without levelup, I am reporting here. My machine also has similar problems with `level`.

```
Ferguss-MacBook-Pro:search-index fergusmcdowall$ nvm use 12
Now using node v12.9.1 (npm v6.10.2)
Ferguss-MacBook-Pro:search-index fergusmcdowall$ npm install levelup@4.1.0

> fsevents@1.2.9 install /Users/fergusmcdowall/projects/node/search-index/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/fergusmcdowall/projects/node/search-index/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> leveldown@5.1.1 install /Users/fergusmcdowall/projects/node/search-index/node_modules/leveldown
> node-gyp-build


> leveldown@3.0.2 install /Users/fergusmcdowall/projects/node/search-index/node_modules/level-out/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.9.1 runtime=node arch=x64 platform=darwin)
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix_sse.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o
  LIBTOOL-STATIC Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.4/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never
      throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../../nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:210:1: note: expanded from here
ToBoolean
^
/Users/fergusmcdowall/Library/Caches/node-gyp/12.9.1/include/node/v8.h:2536:3: note: 'ToBoolean' has
      been explicitly marked deprecated here
  V8_DEPRECATED("ToBoolean can never throw. Use Local version.",
  ^
/Users/fergusmcdowall/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:202:
In file included from ../../nan/nan_converters.h:67:
../../nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can
      never throw. Use Isolate version. [-Wdeprecated-declarations]
X(bool, Boolean)
^
../../nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:217:1: note: expanded from here
BooleanValue
^
/Users/fergusmcdowall/Library/Caches/node-gyp/12.9.1/include/node/v8.h:2574:3: note: 'BooleanValue'
      has been explicitly marked deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/fergusmcdowall/Library/Caches/node-gyp/12.9.1/include/node/v8config.h:311:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/batch.cc:3:
In file included from ../../nan/nan.h:203:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to
      'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~


(lots of C style build errors removed for clarity...)


fatal error: too many errors emitted, stopping now [-ferror-limit=]
14 warnings and 20 errors generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/fergusmcdowall/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/fergusmcdowall/.nvm/versions/node/v12.9.1/bin/node" "/Users/fergusmcdowall/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/fergusmcdowall/projects/node/search-index/node_modules/level-out/node_modules/leveldown
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fergusmcdowall/.npm/_logs/2019-08-29T12_12_12_169Z-debug.log
```

**Comment by vweevers** [comment]
For node 12 you need leveldown >= 5.

**Comment by fergiemcdowall** [comment]
`npm install leveldown@5.1.1` gives a similar error on node 12.9.1

**Comment by vweevers** [comment]
That's curious. Can you share the install log?

**Comment by fergiemcdowall** [comment]
Sure, its pretty similar to the output above. Here is the unabridged version -> [tmp.txt](https://github.com/Level/levelup/files/3555563/tmp.txt)

**Comment by vweevers** [comment]
> > leveldown@3.0.2 install /Users/fergusmcdowall/projects/node/search-index/node_modules/level-out/node_modules/leveldown
> prebuild-install || node-gyp rebuild

That's also leveldown@3?

**Comment by fergiemcdowall** [comment]
Yes and no- the top of the file looks like this ->

```
> leveldown@5.1.1 install /Users/fergusmcdowall/projects/node/search-index/node_modules/leveldown
> node-gyp-build


> leveldown@3.0.2 install /Users/fergusmcdowall/projects/node/search-index/node_modules/level-out/node_modules/leveldown
> prebuild-install || node-gyp rebuild
```

The script seems to be "falling back" on 3.0.2 even though it started to install 5.1.1

**Comment by vweevers** [comment]
It seems that your tree contains two versions of `leveldown`, one as a dependency of `level-out`.

**Comment by fergiemcdowall** [comment]
Ah right yes, if I install in a clean directory it works perfectly. I thought that `npm install leveldown@5.1.1` would always give me 5.1.1, even if I was in a "project" directory 

So in that case, yes, I can get level to install on node v12

Thanks for the help!
