### ISSUE TITLE
deferred-leveldown.js error

### ISSUE THREAD

**Issue by Vanderscycle** [Level/levelup#734]
Hi,

I am using a levelDb for a fast key:value db on a nestJs app. Recently tho I've been getting this error and generally been unable to run the app proprely.

I am a bit confused by there error and this helper package. I posted my issue here because I saw issue #280 which reassemble mine
```
[Nest] 15375  - 2022-01-14, 12:11:36 p.m.     LOG [main.ts] Application is running on: http://127.0.0.1:3100

/home/henri/Documents/a51/node_modules/deferred-leveldown/deferred-leveldown.js:49
      return callback(err || new Error('Database is not open'))
             ^
OpenError: Corruption: no meta-nextfile entry in descriptor
    at /home/henri/Documents/a51/node_modules/levelup/lib/levelup.js:127:23
    at /home/henri/Documents/a51/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at onopen (/home/henri/Documents/a51/node_modules/deferred-leveldown/deferred-leveldown.js:49:14)
    at /home/henri/Documents/a51/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /home/henri/Documents/a51/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
```

Thank you for any help

**Comment by Vanderscycle** [comment]
I repalced level with level-party and it fixed my [issue](https://github.com/Level/party)

**Comment by Vanderscycle** [comment]
I thought that level-party fixed my issue but that wasn't it. I am using 2 leveldb at the same but they are of different addresses.

**Comment by Vanderscycle** [comment]
something was wrong with my machine. works on a docker container :/
